# Generated by Django 4.2.5 on 2023-09-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecomsellerproductupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('imgfile', models.FileField(upload_to='ecom_app/static')),
                ('prod_category', models.CharField(max_length=40)),
                ('prod_size', models.CharField(max_length=10)),
                ('prod_price', models.IntegerField()),
                ('prod_details', models.CharField(max_length=1000)),
            ],
        ),
    ]
