# Generated by Django 4.2.5 on 2023-09-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_ecomsellerproductupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecom_buyer_register_datatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('pw', models.CharField(max_length=15)),
            ],
        ),
    ]
