# Generated by Django 4.2.5 on 2023-09-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_ecom_buyer_register_datatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomsellerproductupload',
            name='login_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
