# Generated by Django 4.2.5 on 2023-09-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_ecom_buyer_wishlist_datatable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecom_buyer_wishlist_datatable',
            old_name='login_id',
            new_name='user_loginid',
        ),
        migrations.AlterField(
            model_name='ecom_buyer_wishlist_datatable',
            name='imgfile',
            field=models.FileField(upload_to=''),
        ),
    ]
