# Generated by Django 4.2.5 on 2023-09-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0008_ecom_buyer_cart_datatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_address_datatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('addressline1', models.CharField(max_length=70)),
                ('addressline2', models.CharField(max_length=70)),
                ('street', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('pin', models.CharField(max_length=10)),
                ('user_loginid', models.IntegerField()),
            ],
        ),
    ]
