# Generated by Django 4.2.5 on 2023-10-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0009_buyer_address_datatable'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_final_confirm_details_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_loginid', models.IntegerField()),
                ('uname', models.CharField(max_length=20)),
                ('delivery_address', models.CharField(max_length=100)),
                ('order_items', models.CharField(max_length=300)),
                ('amount_paid', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('est_delivery_date', models.DateField()),
            ],
        ),
    ]
