# Generated by Django 4.2.5 on 2023-10-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_user_final_confirm_details_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_loginid', models.IntegerField()),
                ('prod_id_list', models.JSONField()),
                ('order_date', models.DateField()),
            ],
        ),
    ]
